CREATE TABLE IF NOT EXISTS public.index_checkpoint
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    contract text COLLATE pg_catalog."default" NOT NULL CHECK (contract = lower(contract)),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    block bigint NOT NULL,
    CONSTRAINT index_checkpoint_pkey PRIMARY KEY (id),
    CONSTRAINT index_checkpoint_block_contract_key UNIQUE (block, contract),
    CONSTRAINT index_checkpoint_contract_key UNIQUE (contract)
) TABLESPACE pg_default;

CREATE TRIGGER handle_index_checkpoint_updated_at
    BEFORE UPDATE 
    ON public.index_checkpoint
    FOR EACH ROW
    EXECUTE FUNCTION extensions.moddatetime('updated_at');

ALTER TABLE IF EXISTS public.index_checkpoint
    OWNER to postgres;

ALTER TABLE public.index_checkpoint ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.index_checkpoint TO postgres;
GRANT SELECT ON TABLE public.index_checkpoint TO anon;
GRANT SELECT, INSERT, UPDATE ON TABLE public.index_checkpoint TO service_role;
