CREATE TABLE IF NOT EXISTS public.services
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    key_manager text COLLATE pg_catalog."default" NOT NULL CHECK (key_manager = lower(key_manager)),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    api_key text COLLATE pg_catalog."default",
    contracts jsonb,
    CONSTRAINT services_pkey PRIMARY KEY (id),
    CONSTRAINT services_key_manager_key UNIQUE (key_manager),
    CONSTRAINT services_api_key_key UNIQUE (api_key)
) TABLESPACE pg_default;

CREATE TRIGGER handle_services_updated_at
    BEFORE UPDATE 
    ON public.services
    FOR EACH ROW
    EXECUTE FUNCTION extensions.moddatetime('updated_at');

ALTER TABLE IF EXISTS public.services
    OWNER to postgres;

ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.services TO postgres;
GRANT SELECT ON TABLE public.services TO anon;
GRANT SELECT, INSERT, UPDATE ON TABLE public.services TO service_role;
