CREATE TABLE IF NOT EXISTS public.staked_token
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    account text COLLATE pg_catalog."default" NOT NULL CHECK (account = lower(account)),
    rewards text COLLATE pg_catalog."default" NOT NULL
) TABLESPACE pg_default;

CREATE INDEX ON public.staked_token (account);

CREATE TRIGGER handle_staked_token_updated_at
    BEFORE UPDATE 
    ON public.staked_token
    FOR EACH ROW
    EXECUTE FUNCTION extensions.moddatetime('updated_at');

ALTER TABLE IF EXISTS public.staked_token
    OWNER to postgres;

ALTER TABLE public.staked_token ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.staked_token TO postgres;
GRANT SELECT ON TABLE public.staked_token TO anon;
GRANT SELECT, INSERT, UPDATE ON TABLE public.staked_token TO service_role;
